import subprocess
print("Libraries installed")
#subprocess.call("sudo mv","config.txt", "/boot")
print("Screen will rotate")
#subprocess.call("sudo mv", "lifelinemain.service","/lib/systemd/system/")
subprocess.Popen("python3","Bedside-Monitor/picode/Main.py")
#subprocess.call("sudo chmod", "644", "/lib/systemd/system/lifelinemain.service")
#subprocess.call("sudo systemctl", "daemon-reload")
#subprocess.call("sudo systemctl", "enable", "lifelinemain.service")
print("Main.py added to boot please reboot!")
